### ISSUE TITLE
Working with Livewire

### ISSUE THREAD

**Issue by clarg18** [maxeckel/alpine-editor#1]
Hello, 

How can I use this with Livewire?

For example:

```html
                    <textarea
                        id="instructions"
                        name="instructions"
                        wire:model="job.instructions"
                        cols="30" rows="10"
                    >
                    </textarea>
```

This is a textarea I have in my livewire component and the model is a eloquent Model's attribute (which is possible in livewire v2). But I cannot see to get this to would with alpine editor.

Any advice welcome!

**Comment by maxeckel** [comment]
Hey @gclark18,

I need to try it again with `wire:model`, last time I checked it wasn't working, because of how `wire:model` works under the hood. But what you could do is use `@entangle` within an alpine component and use `x-model` on the alpine-editor.

That way, whenever the alpine state changes, it will trigger livewire to update.

Hope this helps!
